// Generate the staged b-files and the page data snapshot. Run from repo root:
//   node research/gcd-nim/gen-data.mjs
'use strict';
import { grundy, coprimeMove, commonMove } from './engine.mjs';
import { writeFileSync, mkdirSync } from 'node:fs';

const B = 4096;   // b-file length (n = 0..B)
const P = 160;    // terms embedded in the page

const gCop = grundy(B, coprimeMove);
const gCom = grundy(B, commonMove);

const bfile = (g) => { let s = ''; for (let n = 0; n <= B; n++) s += `${n} ${g[n]}\n`; return s; };

// staged for deposit
const stage = 'oversight/oeis/gcd-nim';
mkdirSync(stage, { recursive: true });
writeFileSync(`${stage}/b-coprime-nim.txt`, bfile(gCop));
writeFileSync(`${stage}/b-common-factor-nim.txt`, bfile(gCom));

// page snapshot (checked-in so the page and verifier share one source of truth)
const snap = {
  note: 'Grundy (nimber) values of a single pile. Generated by research/gcd-nim/gen-data.mjs; verified by verify.mjs (17/17) and verify.py.',
  coprime: Array.from(gCop.slice(0, P)),
  common: Array.from(gCom.slice(0, P)),
};
writeFileSync('research/gcd-nim/data.json', JSON.stringify(snap)); // page recomputes live; this is for cross-checking only

console.log(`wrote b-files (n=0..${B}) to ${stage}/ and data.json (first ${P} terms)`);
console.log('coprime 0..24:', snap.coprime.slice(0, 25).join(','));
console.log('common  0..24:', snap.common.slice(0, 25).join(','));
