/* Count UNDIRECTED Hamiltonian cycles in the n-permutohedron graph:
 * the Cayley graph of S_n generated by adjacent transpositions s_1..s_{n-1}.
 * Vertices: n! permutations; (n-1)-regular.
 *
 * Method: backtracking from a fixed start vertex (the identity), counting
 * directed Hamiltonian cycles and dividing by 2. Pruning:
 *   (1) every still-unvisited vertex must keep degree >= 2 in the subgraph
 *       induced on (unvisited + head + start)  [it needs an in- and out-edge];
 *   (2) (unvisited + head + start) must stay connected (else it can't be one cycle).
 * Bitsets (__int128) make both checks fast for n=5 (120 vertices).
 *
 * Validated targets: n=3 -> 1, n=4 -> 44 (truncated octahedron, OEIS A343433).
 *
 * Build:  gcc -O3 -march=native -o count count.c
 * Run:    ./count 5
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

typedef unsigned __int128 u128;

static int N;                 /* number of vertices = n! */
static u128 ADJ[720];         /* adjacency bitset per vertex (n<=6 -> 720) */
static int  deg[720];
static int  nbr[720][6];      /* neighbor lists (<= n-1 <= 5) */
static int  ndeg[720];

static inline int popc128(u128 x){
  return __builtin_popcountll((uint64_t)x) + __builtin_popcountll((uint64_t)(x>>64));
}

/* ---- build the graph ---- */
static int n_global;
static int perms[720][6];
static int permcount;
static void gen(int *a,int k,int n){
  if(k==n){ memcpy(perms[permcount++],a,sizeof(int)*n); return; }
  for(int i=k;i<n;i++){ int t=a[k];a[k]=a[i];a[i]=t; gen(a,k+1,n); t=a[k];a[k]=a[i];a[i]=t; }
}
static int permindex(int *p,int n){
  for(int i=0;i<permcount;i++){ int ok=1; for(int j=0;j<n;j++) if(perms[i][j]!=p[j]){ok=0;break;} if(ok) return i; }
  return -1;
}
static void build(int n){
  n_global=n; permcount=0;
  int a[6]; for(int i=0;i<n;i++)a[i]=i;
  gen(a,0,n);
  N=permcount;
  for(int i=0;i<N;i++){ ADJ[i]=0; ndeg[i]=0; }
  for(int i=0;i<N;i++){
    for(int s=0;s<n-1;s++){
      int q[6]; memcpy(q,perms[i],sizeof(int)*n);
      int t=q[s]; q[s]=q[s+1]; q[s+1]=t;
      int j=permindex(q,n);
      if(j>=0 && j!=i && !((ADJ[i]>>j)&1)){
        ADJ[i] |= ((u128)1)<<j;
        nbr[i][ndeg[i]++]=j;
      }
    }
    deg[i]=ndeg[i];
  }
}

/* ---- search ---- */
static int START;
static u128 FULL;                /* low-N-bits mask */
static u128 visited;
static int avail[720];           /* # unvisited neighbors, incrementally maintained */
static unsigned long long count_directed;

static inline void mark(int v){
  visited |= ((u128)1)<<v;
  for(int k=0;k<ndeg[v];k++) avail[nbr[v][k]]--;
}
static inline void unmark(int v){
  visited &= ~(((u128)1)<<v);
  for(int k=0;k<ndeg[v];k++) avail[nbr[v][k]]++;
}

/* connectivity: flood from head within allowed = unvisited | start | head;
 * require all allowed vertices reached. */
static inline int connected(int head){
  u128 allowed = ((~visited) & FULL) | (((u128)1)<<START) | (((u128)1)<<head);
  u128 reached = ((u128)1)<<head;
  u128 frontier = reached;
  while(frontier){
    u128 next=0;
    u128 f=frontier;
    while(f){
      int v;
      uint64_t lo=(uint64_t)f;
      if(lo) v=__builtin_ctzll(lo);
      else v=64+__builtin_ctzll((uint64_t)(f>>64));
      next |= ADJ[v];
      f &= f-(u128)1;
    }
    next &= allowed & ~reached;
    reached |= next;
    frontier = next;
  }
  return (allowed & ~reached)==0;
}

/* every unvisited u: avail[u] + (u~head) + (u~start) >= 2 */
static inline int degOK(int head){
  u128 un = (~visited) & FULL;
  u128 f = un;
  u128 hb = ADJ[head];
  u128 sb = (head!=START)? ADJ[START] : (u128)0;
  while(f){
    int u; uint64_t lo=(uint64_t)f;
    if(lo) u=__builtin_ctzll(lo); else u=64+__builtin_ctzll((uint64_t)(f>>64));
    f &= f-(u128)1;
    if(u>=N) continue;
    int d = avail[u] + (int)((hb>>u)&1) + (int)((sb>>u)&1);
    if(d<2) return 0;
  }
  return 1;
}

static void dfs(int head,int depth){
  if(depth==N){
    if((ADJ[head]>>START)&1) count_directed++;
    return;
  }
  for(int k=0;k<ndeg[head];k++){
    int w=nbr[head][k];
    if((visited>>w)&1) continue;
    mark(w);
    if(avail[START]>0 || depth+1==N){
      if(degOK(w) && connected(w)) dfs(w,depth+1);
    }
    unmark(w);
  }
}

int main(int argc,char**argv){
  int n = argc>1? atoi(argv[1]) : 4;
  build(n);
  printf("n=%d: V=%d degree=%d\n", n, N, ndeg[0]);
  FULL = (N>=128) ? (~(u128)0) : ((((u128)1)<<N)-1);
  START=0; visited=0; count_directed=0;
  for(int i=0;i<N;i++) avail[i]=ndeg[i];
  mark(START);
  for(int k=0;k<ndeg[START];k++){
    int w=nbr[START][k];
    mark(w);
    dfs(w,2);
    unmark(w);
    fprintf(stderr,"  first-branch %d/%d done, cum directed=%llu (undirected %llu)\n",
            k+1,ndeg[START],count_directed,count_directed/2);
  }
  printf("n=%d: UNDIRECTED Hamiltonian cycles = %llu\n", n, count_directed/2);
  return 0;
}
