// ca-garden-of-eden — generate b-files + data.json for the staged deposit.
// Run: node research/ca-garden-of-eden/gen-data.mjs
'use strict';
import { goeSizes, imageSizes } from './engine.mjs';
import { writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
const OEIS = join(HERE, '..', '..', 'oversight', 'oeis', 'ca-garden-of-eden');
mkdirSync(OEIS, { recursive: true });

const MAXN = 64;

// The genuinely-OEIS-absent Garden-of-Eden sequences (absence checked 2026-07-19).
const GOE_RULES = [
  [30, 'chaotic; Wolfram/Mathematica default RNG'],
  [110, 'Turing-complete'],
  [184, 'traffic / particle-hopping'],
  [22, 'complex; the count dips at n=4'],
  [126, 'complex'],
  [54, 'class-4 complex'],
  [146, 'complex'],
];

function bfile(fname, series, header) {
  const lines = [`# ${header}`, `# n a(n)  (offset 1). Generated by research/ca-garden-of-eden/gen-data.mjs; verified by verify.mjs.`];
  for (let n = 1; n <= MAXN; n++) lines.push(`${n} ${series[n].toString()}`);
  writeFileSync(join(OEIS, fname), lines.join('\n') + '\n');
  return series.slice(1, 21).map(String); // first 20 for the manifest
}

const data = { generated: 'deterministic', maxN: MAXN, sequences: {} };

for (const [rule, note] of GOE_RULES) {
  const g = goeSizes(rule, MAXN);
  const head = bfile(`b-rule${rule}-goe.txt`, g,
    `Garden-of-Eden count GoE(n) = 2^n - |image| of elementary CA rule ${rule} on a cyclic lattice of length n (${note}). ABSENT from OEIS (checked 2026-07-19).`);
  data.sequences[`rule${rule}-goe`] = { rule, kind: 'goe', note, first20: head };
}

// rule 30 image size (co-sequence; also absent)
{
  const img = imageSizes(30, MAXN);
  const head = bfile('b-rule30-image.txt', img,
    'Image size |image(F_30)| of elementary CA rule 30 on a cyclic lattice of length n (number of configurations WITH a predecessor). GoE(n) = 2^n - this. ABSENT from OEIS (checked 2026-07-19).');
  data.sequences['rule30-image'] = { rule: 30, kind: 'image', note: 'configs with a predecessor', first20: head };
}

writeFileSync(join(HERE, 'data.json'), JSON.stringify(data, null, 2) + '\n');
console.log(`wrote ${Object.keys(data.sequences).length} sequences (n=1..${MAXN}) to ${OEIS}`);
for (const [k, v] of Object.entries(data.sequences)) console.log(`  ${k}: ${v.first20.slice(0, 12).join(',')}...`);
